/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Text: THREE.Mesh;
    Text001: THREE.Mesh;
    Text002: THREE.Mesh;
    Text003: THREE.Mesh;
    Text004: THREE.Mesh;
    Text005: THREE.Mesh;
    Text006: THREE.Mesh;
    Text007: THREE.Mesh;
    Text008: THREE.Mesh;
    Text009: THREE.Mesh;
    Text010: THREE.Mesh;
    Text011: THREE.Mesh;
    Text012: THREE.Mesh;
    Text013: THREE.Mesh;
    Text014: THREE.Mesh;
    Text015: THREE.Mesh;
    Text016: THREE.Mesh;
    Text017: THREE.Mesh;
    Text018: THREE.Mesh;
    Text019: THREE.Mesh;
    Text020: THREE.Mesh;
    Text021: THREE.Mesh;
    Text022: THREE.Mesh;
    Text023: THREE.Mesh;
    Text024: THREE.Mesh;
    Text025: THREE.Mesh;
    Text026: THREE.Mesh;
    Text027: THREE.Mesh;
    Text028: THREE.Mesh;
    Text029: THREE.Mesh;
    Text030: THREE.Mesh;
    Text031: THREE.Mesh;
    Text032: THREE.Mesh;
    Text033: THREE.Mesh;
    Text034: THREE.Mesh;
    Text035: THREE.Mesh;
    Text036: THREE.Mesh;
    Text037: THREE.Mesh;
    Text038: THREE.Mesh;
    Text039: THREE.Mesh;
    Text040: THREE.Mesh;
    Text041: THREE.Mesh;
    Text042: THREE.Mesh;
    Text043: THREE.Mesh;
    Text044: THREE.Mesh;
    Text045: THREE.Mesh;
    Text046: THREE.Mesh;
    Text047: THREE.Mesh;
    Text048: THREE.Mesh;
    Text049: THREE.Mesh;
    Text050: THREE.Mesh;
    Text051: THREE.Mesh;
    Text052: THREE.Mesh;
    Text053: THREE.Mesh;
    Text054: THREE.Mesh;
    Text055: THREE.Mesh;
    Text056: THREE.Mesh;
    Text057: THREE.Mesh;
    Text058: THREE.Mesh;
    Text059: THREE.Mesh;
    Text060: THREE.Mesh;
    Text061: THREE.Mesh;
    Text062: THREE.Mesh;
    Text063: THREE.Mesh;
    Text064: THREE.Mesh;
    Text065: THREE.Mesh;
    Text066: THREE.Mesh;
    Text067: THREE.Mesh;
    Text068: THREE.Mesh;
    Text069: THREE.Mesh;
    Text071: THREE.Mesh;
    Text070: THREE.Mesh;
    Text072: THREE.Mesh;
    Text073: THREE.Mesh;
    Text074: THREE.Mesh;
    Text075: THREE.Mesh;
    Text076: THREE.Mesh;
    Text077: THREE.Mesh;
    Text078: THREE.Mesh;
    Text079: THREE.Mesh;
    Text080: THREE.Mesh;
    Text081: THREE.Mesh;
    Plane: THREE.Mesh;
    Text082: THREE.Mesh;
    Text083: THREE.Mesh;
    Text084: THREE.Mesh;
    Text085: THREE.Mesh;
    Text086: THREE.Mesh;
    Text087: THREE.Mesh;
    Text088: THREE.Mesh;
    Text089: THREE.Mesh;
    Text090: THREE.Mesh;
    Text091: THREE.Mesh;
    Text092: THREE.Mesh;
    Text093: THREE.Mesh;
    Text094: THREE.Mesh;
    Text095: THREE.Mesh;
    Text096: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Touchpad: THREE.Mesh;
    Key: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cube020_1: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    Cube002_2: THREE.Mesh;
    Cube002_3: THREE.Mesh;
  };
  materials: {
    Base: THREE.MeshPhysicalMaterial;
    Black: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    Screen: THREE.MeshPhysicalMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Lenovo LOQ.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Text"
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={nodes.Text.material}
          position={[-0.897, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text001"
          castShadow
          receiveShadow
          geometry={nodes.Text001.geometry}
          material={nodes.Text001.material}
          position={[-0.787, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text002"
          castShadow
          receiveShadow
          geometry={nodes.Text002.geometry}
          material={nodes.Text002.material}
          position={[-0.695, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text003"
          castShadow
          receiveShadow
          geometry={nodes.Text003.geometry}
          material={nodes.Text003.material}
          position={[-0.601, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text004"
          castShadow
          receiveShadow
          geometry={nodes.Text004.geometry}
          material={nodes.Text004.material}
          position={[-0.507, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text005"
          castShadow
          receiveShadow
          geometry={nodes.Text005.geometry}
          material={nodes.Text005.material}
          position={[-0.415, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text006"
          castShadow
          receiveShadow
          geometry={nodes.Text006.geometry}
          material={nodes.Text006.material}
          position={[-0.322, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text007"
          castShadow
          receiveShadow
          geometry={nodes.Text007.geometry}
          material={nodes.Text007.material}
          position={[-0.228, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text008"
          castShadow
          receiveShadow
          geometry={nodes.Text008.geometry}
          material={nodes.Text008.material}
          position={[-0.136, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text009"
          castShadow
          receiveShadow
          geometry={nodes.Text009.geometry}
          material={nodes.Text009.material}
          position={[-0.042, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text010"
          castShadow
          receiveShadow
          geometry={nodes.Text010.geometry}
          material={nodes.Text010.material}
          position={[0.051, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text011"
          castShadow
          receiveShadow
          geometry={nodes.Text011.geometry}
          material={nodes.Text011.material}
          position={[0.143, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text012"
          castShadow
          receiveShadow
          geometry={nodes.Text012.geometry}
          material={nodes.Text012.material}
          position={[0.236, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text013"
          castShadow
          receiveShadow
          geometry={nodes.Text013.geometry}
          material={nodes.Text013.material}
          position={[0.328, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text014"
          castShadow
          receiveShadow
          geometry={nodes.Text014.geometry}
          material={nodes.Text014.material}
          position={[0.423, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text015"
          castShadow
          receiveShadow
          geometry={nodes.Text015.geometry}
          material={nodes.Text015.material}
          position={[0.514, -0.053, -0.241]}
          scale={0.028}
        />
        <mesh
          name="Text016"
          castShadow
          receiveShadow
          geometry={nodes.Text016.geometry}
          material={nodes.Text016.material}
          position={[0.619, -0.053, -0.241]}
          scale={0.024}
        />
        <mesh
          name="Text017"
          castShadow
          receiveShadow
          geometry={nodes.Text017.geometry}
          material={nodes.Text017.material}
          position={[0.718, -0.053, -0.241]}
          scale={0.024}
        />
        <mesh
          name="Text018"
          castShadow
          receiveShadow
          geometry={nodes.Text018.geometry}
          material={nodes.Text018.material}
          position={[0.798, -0.053, -0.241]}
          scale={0.024}
        />
        <mesh
          name="Text019"
          castShadow
          receiveShadow
          geometry={nodes.Text019.geometry}
          material={nodes.Text019.material}
          position={[0.884, -0.053, -0.241]}
          scale={0.024}
        />
        <mesh
          name="Text020"
          castShadow
          receiveShadow
          geometry={nodes.Text020.geometry}
          material={nodes.Text020.material}
          position={[-0.89, -0.052, -0.162]}
          scale={0.028}
        />
        <mesh
          name="Text021"
          castShadow
          receiveShadow
          geometry={nodes.Text021.geometry}
          material={nodes.Text021.material}
          position={[-0.793, -0.052, -0.162]}
          scale={0.028}
        />
        <mesh
          name="Text022"
          castShadow
          receiveShadow
          geometry={nodes.Text022.geometry}
          material={nodes.Text022.material}
          position={[-0.683, -0.052, -0.162]}
          scale={0.028}
        />
        <mesh
          name="Text023"
          castShadow
          receiveShadow
          geometry={nodes.Text023.geometry}
          material={nodes.Text023.material}
          position={[-0.576, -0.052, -0.162]}
          scale={0.028}
        />
        <mesh
          name="Text024"
          castShadow
          receiveShadow
          geometry={nodes.Text024.geometry}
          material={nodes.Text024.material}
          position={[-0.472, -0.052, -0.162]}
          scale={0.028}
        />
        <mesh
          name="Text025"
          castShadow
          receiveShadow
          geometry={nodes.Text025.geometry}
          material={nodes.Text025.material}
          position={[-0.365, -0.052, -0.162]}
          scale={0.028}
        />
        <mesh
          name="Text026"
          castShadow
          receiveShadow
          geometry={nodes.Text026.geometry}
          material={nodes.Text026.material}
          position={[-0.26, -0.052, -0.162]}
          scale={0.028}
        />
        <mesh
          name="Text027"
          castShadow
          receiveShadow
          geometry={nodes.Text027.geometry}
          material={nodes.Text027.material}
          position={[-0.154, -0.052, -0.162]}
          scale={0.028}
        />
        <mesh
          name="Text028"
          castShadow
          receiveShadow
          geometry={nodes.Text028.geometry}
          material={nodes.Text028.material}
          position={[-0.049, -0.052, -0.162]}
          scale={0.028}
        />
        <mesh
          name="Text029"
          castShadow
          receiveShadow
          geometry={nodes.Text029.geometry}
          material={nodes.Text029.material}
          position={[0.056, -0.052, -0.162]}
          scale={0.028}
        />
        <mesh
          name="Text030"
          castShadow
          receiveShadow
          geometry={nodes.Text030.geometry}
          material={nodes.Text030.material}
          position={[0.163, -0.052, -0.162]}
          scale={0.028}
        />
        <mesh
          name="Text031"
          castShadow
          receiveShadow
          geometry={nodes.Text031.geometry}
          material={nodes.Text031.material}
          position={[0.265, -0.052, -0.164]}
          scale={0.028}
        />
        <mesh
          name="Text032"
          castShadow
          receiveShadow
          geometry={nodes.Text032.geometry}
          material={nodes.Text032.material}
          position={[0.259, -0.052, -0.127]}
          scale={[0.058, 0.028, 0.028]}
        />
        <mesh
          name="Text033"
          castShadow
          receiveShadow
          geometry={nodes.Text033.geometry}
          material={nodes.Text033.material}
          position={[0.37, -0.052, -0.162]}
          scale={0.028}
        />
        <mesh
          name="Text034"
          castShadow
          receiveShadow
          geometry={nodes.Text034.geometry}
          material={nodes.Text034.material}
          position={[0.532, -0.052, -0.15]}
          scale={0.026}
        />
        <mesh
          name="Text035"
          castShadow
          receiveShadow
          geometry={nodes.Text035.geometry}
          material={nodes.Text035.material}
          position={[0.649, -0.052, -0.16]}
          scale={0.022}
        />
        <mesh
          name="Text036"
          castShadow
          receiveShadow
          geometry={nodes.Text036.geometry}
          material={nodes.Text036.material}
          position={[0.723, -0.052, -0.154]}
          scale={0.028}
        />
        <mesh
          name="Text037"
          castShadow
          receiveShadow
          geometry={nodes.Text037.geometry}
          material={nodes.Text037.material}
          position={[0.808, -0.052, -0.154]}
          scale={0.028}
        />
        <mesh
          name="Text038"
          castShadow
          receiveShadow
          geometry={nodes.Text038.geometry}
          material={nodes.Text038.material}
          position={[0.896, -0.052, -0.163]}
          scale={[0.058, 0.028, 0.028]}
        />
        <mesh
          name="Text039"
          castShadow
          receiveShadow
          geometry={nodes.Text039.geometry}
          material={nodes.Text039.material}
          position={[-0.89, -0.052, -0.049]}
          scale={0.028}
        />
        <mesh
          name="Text040"
          castShadow
          receiveShadow
          geometry={nodes.Text040.geometry}
          material={nodes.Text040.material}
          position={[-0.749, -0.052, -0.055]}
          scale={0.036}
        />
        <mesh
          name="Text041"
          castShadow
          receiveShadow
          geometry={nodes.Text041.geometry}
          material={nodes.Text041.material}
          position={[-0.644, -0.052, -0.055]}
          scale={0.036}
        />
        <mesh
          name="Text042"
          castShadow
          receiveShadow
          geometry={nodes.Text042.geometry}
          material={nodes.Text042.material}
          position={[-0.537, -0.052, -0.055]}
          scale={0.036}
        />
        <mesh
          name="Text043"
          castShadow
          receiveShadow
          geometry={nodes.Text043.geometry}
          material={nodes.Text043.material}
          position={[-0.433, -0.052, -0.055]}
          scale={0.036}
        />
        <mesh
          name="Text044"
          castShadow
          receiveShadow
          geometry={nodes.Text044.geometry}
          material={nodes.Text044.material}
          position={[-0.326, -0.052, -0.055]}
          scale={0.036}
        />
        <mesh
          name="Text045"
          castShadow
          receiveShadow
          geometry={nodes.Text045.geometry}
          material={nodes.Text045.material}
          position={[-0.221, -0.052, -0.055]}
          scale={0.036}
        />
        <mesh
          name="Text046"
          castShadow
          receiveShadow
          geometry={nodes.Text046.geometry}
          material={nodes.Text046.material}
          position={[-0.115, -0.052, -0.055]}
          scale={0.036}
        />
        <mesh
          name="Text047"
          castShadow
          receiveShadow
          geometry={nodes.Text047.geometry}
          material={nodes.Text047.material}
          position={[-0.009, -0.052, -0.055]}
          scale={0.036}
        />
        <mesh
          name="Text048"
          castShadow
          receiveShadow
          geometry={nodes.Text048.geometry}
          material={nodes.Text048.material}
          position={[0.094, -0.052, -0.055]}
          scale={0.036}
        />
        <mesh
          name="Text049"
          castShadow
          receiveShadow
          geometry={nodes.Text049.geometry}
          material={nodes.Text049.material}
          position={[0.201, -0.052, -0.055]}
          scale={0.036}
        />
        <mesh
          name="Text050"
          castShadow
          receiveShadow
          geometry={nodes.Text050.geometry}
          material={nodes.Text050.material}
          position={[0.308, -0.052, -0.063]}
          scale={[0.02, 0.036, 0.02]}
        />
        <mesh
          name="Text051"
          castShadow
          receiveShadow
          geometry={nodes.Text051.geometry}
          material={nodes.Text051.material}
          position={[0.415, -0.052, -0.063]}
          scale={[0.02, 0.036, 0.02]}
        />
        <mesh
          name="Text052"
          castShadow
          receiveShadow
          geometry={nodes.Text052.geometry}
          material={nodes.Text052.material}
          position={[0.521, -0.052, -0.063]}
          scale={[0.023, 0.041, 0.023]}
        />
        <mesh
          name="Text053"
          castShadow
          receiveShadow
          geometry={nodes.Text053.geometry}
          material={nodes.Text053.material}
          position={[0.624, -0.052, -0.054]}
          scale={[0.037, 0.067, 0.037]}
        />
        <mesh
          name="Text054"
          castShadow
          receiveShadow
          geometry={nodes.Text054.geometry}
          material={nodes.Text054.material}
          position={[0.713, -0.052, -0.054]}
          scale={[0.037, 0.067, 0.037]}
        />
        <mesh
          name="Text055"
          castShadow
          receiveShadow
          geometry={nodes.Text055.geometry}
          material={nodes.Text055.material}
          position={[0.801, -0.052, -0.054]}
          scale={[0.037, 0.067, 0.037]}
        />
        <mesh
          name="Text056"
          castShadow
          receiveShadow
          geometry={nodes.Text056.geometry}
          material={nodes.Text056.material}
          position={[0.886, -0.052, 0.015]}
          scale={[0.037, 0.067, 0.037]}
        />
        <mesh
          name="Text057"
          castShadow
          receiveShadow
          geometry={nodes.Text057.geometry}
          material={nodes.Text057.material}
          position={[0.886, -0.052, 0.217]}
          scale={[0.023, 0.042, 0.023]}
        />
        <mesh
          name="Text058"
          castShadow
          receiveShadow
          geometry={nodes.Text058.geometry}
          material={nodes.Text058.material}
          position={[-0.89, -0.052, 0.058]}
          scale={0.028}
        />
        <mesh
          name="Text059"
          castShadow
          receiveShadow
          geometry={nodes.Text059.geometry}
          material={nodes.Text059.material}
          position={[-0.717, -0.052, 0.051]}
          scale={0.036}
        />
        <mesh
          name="Text060"
          castShadow
          receiveShadow
          geometry={nodes.Text060.geometry}
          material={nodes.Text060.material}
          position={[-0.611, -0.052, 0.051]}
          scale={0.036}
        />
        <mesh
          name="Text061"
          castShadow
          receiveShadow
          geometry={nodes.Text061.geometry}
          material={nodes.Text061.material}
          position={[-0.505, -0.052, 0.051]}
          scale={0.036}
        />
        <mesh
          name="Text062"
          castShadow
          receiveShadow
          geometry={nodes.Text062.geometry}
          material={nodes.Text062.material}
          position={[-0.4, -0.052, 0.051]}
          scale={0.036}
        />
        <mesh
          name="Text063"
          castShadow
          receiveShadow
          geometry={nodes.Text063.geometry}
          material={nodes.Text063.material}
          position={[-0.294, -0.052, 0.051]}
          scale={0.036}
        />
        <mesh
          name="Text064"
          castShadow
          receiveShadow
          geometry={nodes.Text064.geometry}
          material={nodes.Text064.material}
          position={[-0.19, -0.052, 0.051]}
          scale={0.036}
        />
        <mesh
          name="Text065"
          castShadow
          receiveShadow
          geometry={nodes.Text065.geometry}
          material={nodes.Text065.material}
          position={[-0.078, -0.052, 0.045]}
          scale={[0.03, 0.03, 0.028]}
        />
        <mesh
          name="Text066"
          castShadow
          receiveShadow
          geometry={nodes.Text066.geometry}
          material={nodes.Text066.material}
          position={[0.022, -0.052, 0.051]}
          scale={0.036}
        />
        <mesh
          name="Text067"
          castShadow
          receiveShadow
          geometry={nodes.Text067.geometry}
          material={nodes.Text067.material}
          position={[0.128, -0.052, 0.051]}
          scale={0.036}
        />
        <mesh
          name="Text068"
          castShadow
          receiveShadow
          geometry={nodes.Text068.geometry}
          material={nodes.Text068.material}
          position={[0.234, -0.052, 0.042]}
          scale={0.033}
        />
        <mesh
          name="Text069"
          castShadow
          receiveShadow
          geometry={nodes.Text069.geometry}
          material={nodes.Text069.material}
          position={[0.339, -0.052, 0.051]}
          scale={0.033}
        />
        <mesh
          name="Text071"
          castShadow
          receiveShadow
          geometry={nodes.Text071.geometry}
          material={nodes.Text071.material}
          position={[0.527, -0.052, 0.059]}
          scale={0.026}
        />
        <mesh
          name="Text070"
          castShadow
          receiveShadow
          geometry={nodes.Text070.geometry}
          material={nodes.Text070.material}
          position={[0.533, -0.052, 0.16]}
          scale={0.026}
        />
        <mesh
          name="Text072"
          castShadow
          receiveShadow
          geometry={nodes.Text072.geometry}
          material={nodes.Text072.material}
          position={[0.624, -0.052, 0.05]}
          scale={[0.037, 0.067, 0.037]}
        />
        <mesh
          name="Text073"
          castShadow
          receiveShadow
          geometry={nodes.Text073.geometry}
          material={nodes.Text073.material}
          position={[0.624, -0.052, 0.051]}
          scale={[0.037, 0.067, 0.037]}
        />
        <mesh
          name="Text074"
          castShadow
          receiveShadow
          geometry={nodes.Text074.geometry}
          material={nodes.Text074.material}
          position={[0.624, -0.052, 0.154]}
          scale={[0.037, 0.067, 0.037]}
        />
        <mesh
          name="Text075"
          castShadow
          receiveShadow
          geometry={nodes.Text075.geometry}
          material={nodes.Text075.material}
          position={[0.713, -0.052, 0.049]}
          scale={[0.037, 0.067, 0.037]}
        />
        <mesh
          name="Text076"
          castShadow
          receiveShadow
          geometry={nodes.Text076.geometry}
          material={nodes.Text076.material}
          position={[0.713, -0.052, 0.153]}
          scale={[0.037, 0.067, 0.037]}
        />
        <mesh
          name="Text077"
          castShadow
          receiveShadow
          geometry={nodes.Text077.geometry}
          material={nodes.Text077.material}
          position={[0.801, -0.052, 0.048]}
          scale={[0.037, 0.067, 0.037]}
        />
        <mesh
          name="Text078"
          castShadow
          receiveShadow
          geometry={nodes.Text078.geometry}
          material={nodes.Text078.material}
          position={[0.801, -0.052, 0.152]}
          scale={[0.037, 0.067, 0.037]}
        />
        <mesh
          name="Text079"
          castShadow
          receiveShadow
          geometry={nodes.Text079.geometry}
          material={nodes.Text079.material}
          position={[0.624, -0.052, 0.258]}
          scale={[0.037, 0.067, 0.037]}
        />
        <mesh
          name="Text080"
          castShadow
          receiveShadow
          geometry={nodes.Text080.geometry}
          material={nodes.Text080.material}
          position={[0.837, -0.052, 0.284]}
          scale={[0.015, 0.028, 0.015]}
        />
        <mesh
          name="Text081"
          castShadow
          receiveShadow
          geometry={nodes.Text081.geometry}
          material={nodes.Text081.material}
          position={[0.741, -0.052, 0.289]}
          scale={[0.015, 0.028, 0.015]}
        />
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={nodes.Plane.material}
          position={[0.809, -0.052, 0.237]}
          scale={0.003}
        />
        <mesh
          name="Text082"
          castShadow
          receiveShadow
          geometry={nodes.Text082.geometry}
          material={nodes.Text082.material}
          position={[-0.885, -0.052, 0.162]}
          scale={0.028}
        />
        <mesh
          name="Text083"
          castShadow
          receiveShadow
          geometry={nodes.Text083.geometry}
          material={nodes.Text083.material}
          position={[-0.663, -0.052, 0.154]}
          scale={0.036}
        />
        <mesh
          name="Text084"
          castShadow
          receiveShadow
          geometry={nodes.Text084.geometry}
          material={nodes.Text084.material}
          position={[-0.556, -0.052, 0.154]}
          scale={0.036}
        />
        <mesh
          name="Text085"
          castShadow
          receiveShadow
          geometry={nodes.Text085.geometry}
          material={nodes.Text085.material}
          position={[-0.452, -0.052, 0.154]}
          scale={0.036}
        />
        <mesh
          name="Text086"
          castShadow
          receiveShadow
          geometry={nodes.Text086.geometry}
          material={nodes.Text086.material}
          position={[-0.346, -0.052, 0.154]}
          scale={0.036}
        />
        <mesh
          name="Text087"
          castShadow
          receiveShadow
          geometry={nodes.Text087.geometry}
          material={nodes.Text087.material}
          position={[-0.24, -0.052, 0.154]}
          scale={0.036}
        />
        <mesh
          name="Text088"
          castShadow
          receiveShadow
          geometry={nodes.Text088.geometry}
          material={nodes.Text088.material}
          position={[-0.135, -0.052, 0.154]}
          scale={0.036}
        />
        <mesh
          name="Text089"
          castShadow
          receiveShadow
          geometry={nodes.Text089.geometry}
          material={nodes.Text089.material}
          position={[-0.029, -0.052, 0.154]}
          scale={0.036}
        />
        <mesh
          name="Text090"
          castShadow
          receiveShadow
          geometry={nodes.Text090.geometry}
          material={nodes.Text090.material}
          position={[0.084, -0.052, 0.149]}
          scale={0.033}
        />
        <mesh
          name="Text091"
          castShadow
          receiveShadow
          geometry={nodes.Text091.geometry}
          material={nodes.Text091.material}
          position={[0.188, -0.052, 0.149]}
          scale={0.033}
        />
        <mesh
          name="Text092"
          castShadow
          receiveShadow
          geometry={nodes.Text092.geometry}
          material={nodes.Text092.material}
          position={[0.294, -0.052, 0.148]}
          scale={0.028}
        />
        <mesh
          name="Text093"
          castShadow
          receiveShadow
          geometry={nodes.Text093.geometry}
          material={nodes.Text093.material}
          position={[-0.885, -0.052, 0.271]}
          scale={0.028}
        />
        <mesh
          name="Text094"
          castShadow
          receiveShadow
          geometry={nodes.Text094.geometry}
          material={nodes.Text094.material}
          position={[-0.769, -0.052, 0.271]}
          scale={0.028}
        />
        <mesh
          name="Text095"
          castShadow
          receiveShadow
          geometry={nodes.Text095.geometry}
          material={nodes.Text095.material}
          position={[-0.556, -0.052, 0.271]}
          scale={0.028}
        />
        <mesh
          name="Text096"
          castShadow
          receiveShadow
          geometry={nodes.Text096.geometry}
          material={nodes.Text096.material}
          position={[0.076, -0.052, 0.271]}
          scale={0.028}
        />
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.Base}
          position={[0.78, -0.06, -0.444]}
          scale={[1.198, 0.838, 0.964]}
        />
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials.Base}
          position={[-0.735, -0.06, -0.444]}
          scale={[1.198, 0.838, 0.964]}
        />
        <mesh
          name="Touchpad"
          castShadow
          receiveShadow
          geometry={nodes.Touchpad.geometry}
          material={materials.Base}
          position={[-0.204, -0.058, 0.616]}
          scale={0.992}
        />
        <mesh
          name="Key"
          castShadow
          receiveShadow
          geometry={nodes.Key.geometry}
          material={materials.Black}
          position={[0.067, -0.056, -0.011]}
          scale={[0.487, 0.487, 0.473]}
        />
        <group name="Lower_Part" position={[0.071, -0.061, 0.205]} scale={[1, 1, 0.972]}>
          <mesh
            name="Cube020"
            castShadow
            receiveShadow
            geometry={nodes.Cube020.geometry}
            material={materials.Base}
          />
          <mesh
            name="Cube020_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube020_1.geometry}
            material={materials['Material.001']}
          />
        </group>
        <group
          name="Uppper_Part"
          position={[0.027, 0.659, -0.44]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.009, 0.029, 1.105]}
        >
          <mesh
            name="Cube002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials.Screen}
          />
          <mesh
            name="Cube002_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_2.geometry}
            material={materials.Base}
          />
          <mesh
            name="Cube002_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_3.geometry}
            material={materials.Black}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/Lenovo LOQ.glb');
